"""
Dummy frontend implementation for testing and development.

This frontend returns canned responses without real audio processing.
"""

from typing import Any

from audio_agent.frontend.model_frontend import BaseModelFrontend, UnifiedFrontendInput


class DummyFrontend(BaseModelFrontend):
    """
    Dummy frontend that returns mock evidence.

    Useful for:
    - Testing the framework end-to-end
    - Development without GPU/API dependencies
    - Demonstrating the expected interface
    """

    @property
    def name(self) -> str:
        return "dummy_frontend"

    def initialize_model(self) -> dict:
        """
        Initialize dummy model handle.

        Real providers should initialize SDK clients or local model handles here.
        """
        return {"provider": "dummy", "ready": True}

    def call_model(self, model_input: UnifiedFrontendInput) -> str:
        """
        Return mock model output as plain text caption.
        """
        if model_input.metadata.get("task") == "frontend_followup":
            prompt = model_input.user_payload.get("followup_prompt", "")
            return (
                f"[Dummy Follow-up] Answering the planner request for "
                f"'{model_input.question}': {prompt}"
            )

        prompt = (
            model_input.metadata.get("question_oriented_prompt")
            or "No customized prompt available."
        )
        return (
            f"General Caption: The audio appears to include speech content relevant to the question "
            f"'{model_input.question}'. There may also be background sounds.\n\n"
            f"Focus Point: {prompt}\n\n"
            f"Proposed Answer / Confidence: It likely contains relevant speech (confidence: 0.6).\n\n"
            f"Uncertainties / Verification Needs: Exact lexical details are unclear; ASR tool could improve transcription accuracy."
        )

    def generate_final_answer(
        self,
        question: str,
        audio_paths: list[str],
        context: dict[str, Any],
    ) -> str:
        """
        Return a mock final answer as JSON with final_answer and rationale keys.

        This allows testing the final answer flow without real model calls.
        """
        evidence_count = len(context.get("evidence_log", []))
        final_answer = (
            f"[Dummy Final Answer] Based on {evidence_count} evidence items for: {question}\n\n"
            "This is a placeholder final answer generated by the dummy frontend."
        )
        rationale = (
            f"Dummy reasoning: I reviewed {evidence_count} evidence items and concluded "
            "that the audio contains relevant content matching the user's question."
        )
        import json
        return json.dumps({"final_answer": final_answer, "rationale": rationale}, ensure_ascii=False)
