"""
Agent state definition for LangGraph.

This module defines the central state object that flows through the graph.
Uses TypedDict for LangGraph compatibility with Pydantic models as field types.
"""

from typing import TypedDict, Annotated, Any
from operator import add

from audio_agent.core.schemas import (
    FrontendOutput,
    InitialPlan,
    EvidenceItem,
    ToolCallRecord,
    PlannerDecision,
    FinalAnswer,
    ToolResult,
    AudioItem,
    FormatCheckResult,
)
from audio_agent.core.constants import AgentStatus


def _replace_value(existing: any, new: any) -> any:
    """Reducer that replaces the existing value with the new value."""
    return new


def _append_to_list(existing: list, new: list) -> list:
    """Reducer that appends new items to the existing list."""
    if existing is None:
        existing = []
    if new is None:
        return existing
    return existing + new


class AgentState(TypedDict, total=False):
    """
    Central state object for the audio agent graph.
    
    This state flows through all nodes. LangGraph uses reducers (via Annotated)
    to merge partial state updates from each node.
    
    Fields:
        question: The user's question about the audio
        original_audio_paths: Original paths to the audio files (for reference)
        audio_list: List of audio files (original + generated by tools)
        temp_dir: Temporary directory for audio files
        initial_frontend_output: Output from the frontend LALM
        initial_plan: Initial planner output generated from question only
        evidence_log: Accumulated evidence items (append-only)
        tool_call_history: History of tool invocations (append-only)
        initial_plan_trace: Log of initial planning outputs (append-only)
        planner_trace: Log of planner action decisions (append-only)
        current_decision: Latest planner decision
        latest_tool_results: Most recent tool execution results for the
            current round (transient). One round can carry multiple tool
            results when the planner emitted parallel tool calls.
        final_answer: The final answer if agent completed successfully
        error_message: Error message if agent failed
        step_count: Current step number
        max_steps: Maximum allowed steps
        status: Current agent status
    """
    # Core inputs (set once at start)
    question: str
    original_audio_paths: list[str]  # Keep original paths for reference
    temp_dir: str  # Temp directory for audio files
    
    # Audio list (original + generated by tools)
    # Uses replace reducer since we replace the whole list when adding new audio
    audio_list: Annotated[list[AudioItem], _replace_value]
    
    # Frontend output (set once after frontend runs)
    initial_frontend_output: FrontendOutput | None
    initial_plan: InitialPlan | None
    
    # Accumulated data (append-only lists)
    evidence_log: Annotated[list[EvidenceItem], _append_to_list]
    tool_call_history: Annotated[list[ToolCallRecord], _append_to_list]
    initial_plan_trace: Annotated[list[InitialPlan], _append_to_list]
    planner_trace: Annotated[list[PlannerDecision], _append_to_list]
    
    # Current state (overwritten each cycle)
    current_decision: PlannerDecision | None
    latest_tool_results: list[ToolResult]
    latest_frontend_followup_output: FrontendOutput | None
    
    # Intent extracted during planning
    clarified_intent: str | None
    expected_output_format: str | None
    
    # Question-oriented prompt for frontend captioning
    question_oriented_prompt: str | None
    
    # Format check (mandatory format validation before final answer)
    format_check_result: FormatCheckResult | None
    format_check_count: int  # Track number of format checks to prevent loops
    
    # Frontend-generated rationale for the final answer
    final_answer_rationale: str | None
    
    # Evidence summary (consolidated narrative before final answer)
    evidence_summary: str | None
    
    # Runtime configuration (feature flags passed from AgentConfig)
    config: dict[str, Any] | None
    
    # Final outputs
    final_answer: FinalAnswer | None
    error_message: str | None
    
    # Counters and status
    step_count: int
    max_steps: int
    status: AgentStatus


def create_initial_state(
    question: str,
    audio_paths: list[str],
    max_steps: int = 10,
    temp_dir: str | None = None,
    audio_list: list[AudioItem] | None = None,
    config: dict[str, Any] | None = None,
) -> AgentState:
    """
    Factory function to create a valid initial agent state.
    
    Args:
        question: The user's question about the audio
        audio_paths: List of paths to audio files
        max_steps: Maximum steps before exhaustion
        temp_dir: Temp directory for audio files (set by AudioAgent)
        audio_list: List of audio items (set by AudioAgent)
    
    Returns:
        A properly initialized AgentState
    
    Raises:
        ValueError: If question is empty or audio_paths is empty
    """
    if not question or not question.strip():
        raise ValueError("question must be a non-empty string")
    if not audio_paths or len(audio_paths) == 0:
        raise ValueError("audio_paths must contain at least one path")
    for path in audio_paths:
        if not path or not path.strip():
            raise ValueError("audio_paths cannot contain empty strings")
    if max_steps < 1:
        raise ValueError("max_steps must be at least 1")
    
    return AgentState(
        question=question.strip(),
        original_audio_paths=[p.strip() for p in audio_paths],
        temp_dir=temp_dir or "",
        audio_list=audio_list or [],
        initial_frontend_output=None,
        initial_plan=None,
        evidence_log=[],
        tool_call_history=[],
        initial_plan_trace=[],
        planner_trace=[],
        current_decision=None,
        latest_tool_results=[],
        latest_frontend_followup_output=None,
        clarified_intent=None,
        expected_output_format=None,
        question_oriented_prompt=None,
        format_check_result=None,
        format_check_count=0,
        final_answer_rationale=None,
        evidence_summary=None,
        config=config,
        final_answer=None,
        error_message=None,
        step_count=0,
        max_steps=max_steps,
        status=AgentStatus.RUNNING,
    )
